import java.util.ArrayList;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.scene.shape.StrokeType;

/**
 * Food generated by the GameField for the Snake to eat and grow
 * @author Matthew Below
 */
public class Food extends Circle
{
    private double x;
    private double y;
    
    private ArrayList<Color> foodColors;
    private ArrayList<Double> foodSizes;
    
    private int colorPos = 0;
    private int sizePos = 0;
    
    public Food(MainMenu menu)
    {
        super(6);
        
        if(menu.getSettings().getFoodColors().isEmpty()) {
            foodColors = new ArrayList<Color>();
            foodColors.add(Color.ORANGE);
        } else foodColors = menu.getSettings().getFoodColors();
        
        if(menu.getSettings().getFoodSizes().isEmpty()) {
            foodSizes = new ArrayList<Double>();
            foodSizes.add(6.0);
        } else foodSizes = menu.getSettings().getFoodSizes();
        
        setStroke(menu.getSettings().foodStrColor);
        setStrokeWidth(menu.getSettings().foodStrWidth);
        setStrokeType(StrokeType.OUTSIDE);
        setFill(foodColors.get(0));
        setRadius(foodSizes.get(0));
    }
   
    public double getX()
    {
        return x;
    }
    
    public void setX(double x)
    {
        this.x = x;
    }
    
    public double getY()
    {
        return y;
    }
    
    public void setY(double y)
    {
        this.y = y;
    }
    
    public void updateFrame()
    {
        updateColors();
        updateSizes();
    }
    
    public void updateColors()
    {
        this.setFill(foodColors.get(colorPos));
        colorPos = (colorPos + 1) % foodColors.size();
    }
    
    public void updateSizes()
    {
        this.setRadius(foodSizes.get(sizePos));
        sizePos = (sizePos + 1) % foodSizes.size();
    }
}
