import javafx.scene.shape.Circle;

/**
 * Food generated by the GameField for the Snake to eat and grow
 * @author Matthew Below
 */
public class Food extends Circle
{
    private double x;
    private double y;
    
    public Food()
    {
        super(6);
        setStyle("-fx-stroke: black; -fx-fill: orange; -fx-stroke-width: 2;");
    }
    
    public Food(double x, double y)
    {
        super(6);
        setStyle("-fx-stroke: black; -fx-fill: orange; -fx-stroke-width: 2;");
        this.x = x;
        this.y = y;
    }
    
    public double getX()
    {
        return x;
    }
    
    public void setX(double x)
    {
        this.x = x;
    }
    
    public double getY()
    {
        return y;
    }
    
    public void setY(double y)
    {
        this.y = y;
    }
    
    public void updateFrame()
    {
        
    }
}
